# Generated by Django 6.1.1 on 2026-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="chore",
            name="rotation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="household",
            name="invite_code",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
